addons:
  apt:
    packages:
    - bc
after_success:
- coveralls
before_install:
- pip install coveralls
- if [ -z "$_COMMAND" ]; then export _COMMAND=test; fi
- if [ -z "$_DJANGO" ]; then export _DJANGO=5.2.10; export _DJANGO_STORAGES=1.14; export _BOTO3=1.26.0; fi
env:
- _BOTO3=1.26.0 _DJANGO=5.0.10 _DJANGO_STORAGES=1.14
- _BOTO3=1.26.0 _DJANGO=5.1.5 _DJANGO_STORAGES=1.14
- _BOTO3=1.26.0 _DJANGO=5.2.10 _DJANGO_STORAGES=1.14
install:
- pip install django-nose
- pip install pylint
- if [ -n "$_BOTO3" ]; then pip install boto3==$_BOTO3; fi
- if [ -n "$_DJANGO" ]; then pip install Django==$_DJANGO django-storages==$_DJANGO_STORAGES; fi
language: python
matrix:
  include:
  - env: _COMMAND=pylint
    python: 3.10
notifications:
  email:
    on_failure: change
    on_success: change
python:
- "3.10"
- "3.11"
- "3.12"
script:
- make $_COMMAND
sudo: false
